#include "stream_startup.h"

#include "c_subsys.h"
#include "cd_controller.h"
#include "cfg.h"
#include "core.h"
#include "disc.h"
#include "execution_services.h"
#include "game.h"
#include "guest_execution.h"

#include <array>
#include <cstdlib>
#include <lucent/log.h>

namespace x4::stream_startup {
namespace {

// SLUS_005.61 0x80018788..0x80018ACC. The matching decomp deliberately leaves this body as
// INCLUDE_ASM; every address and edge below is therefore derived from the authenticated executable.
constexpr std::uint32_t kSetStreamMode = 0x800190F0u;
constexpr std::uint32_t kDecDctReset = 0x800ECDE0u;
constexpr std::uint32_t kDecDctOutCallback = 0x800ED084u;
constexpr std::uint32_t kStSetRing = 0x800E5A9Cu;
constexpr std::uint32_t kStSetStream = 0x800E8278u;
constexpr std::uint32_t kResetMovieState = 0x800192F8u;
constexpr std::uint32_t kSetCdVolume = 0x80018FD0u;
constexpr std::uint32_t kCdIntToPos = 0x800E61BCu;
constexpr std::uint32_t kCdPosToInt = 0x800E62C0u;
constexpr std::uint32_t kPrepareFirstFrame = 0x80019228u;
constexpr std::uint32_t kStGetNext = 0x800E83F4u;
constexpr std::uint32_t kDecDctVlc = 0x800ED574u;
constexpr std::uint32_t kStFreeRing = 0x800E8300u;

constexpr std::uint32_t kDecDctOutput = 0x80019100u;
constexpr std::uint32_t kStCdInterrupt = 0x800E80B0u;
constexpr std::uint32_t kStVblankCallback = 0x80019208u;

constexpr std::uint32_t kStreamArg2 = 0x801395E0u;
constexpr std::uint32_t kFrameHeaderRemaining = 0x801395B0u;
constexpr std::uint32_t kFrameHeaderCopy = 0x801395F0u;
constexpr std::uint32_t kFrameWidth = 0x80139600u;
constexpr std::uint32_t kFrameHeight = 0x80139602u;
constexpr std::uint32_t kVlcTableIndex = 0x801395ECu;
constexpr std::uint32_t kVlcTables = 0x801395D4u;
constexpr std::uint32_t kStreamStartLba = 0x80139650u;
constexpr std::uint32_t kStreamLocation = 0x80139654u;
constexpr std::uint32_t kStreamPosition = 0x80139648u;
constexpr std::uint32_t kStreamFilter = 0x80175EE8u;
constexpr std::uint32_t kStreamFlavor = 0x800F1D88u;
constexpr std::uint32_t kStSectorMode = 0x8013E1C0u;
constexpr std::uint32_t kReadyCallbackSlot = 0x8011DD20u;

constexpr std::uint32_t kDefaultReadMode = 328u;
constexpr std::uint32_t kAlternateReadMode = 456u;
constexpr std::uint32_t kFirstFrameWaitLimit = 601u;

void tick(Core &core, std::uint32_t ticks) {
  psx::cpu::accountGuestInstructions(core, ticks);
}

void call(Core &core, GuestDispatch dispatch, std::uint32_t entry, std::uint32_t returnAddress, std::uint32_t ticks) {
  core.r[31] = returnAddress;
  tick(core, ticks);
  dispatch(&core, entry);
}

void serviceFields(Core &core, FieldService serviceField, std::uint32_t count) {
  for (std::uint32_t field = 0; field < count; ++field) {
    serviceField(core);
  }
}

std::uint8_t bcd(std::uint32_t value) {
  return static_cast<std::uint8_t>(((value / 10u) << 4u) | (value % 10u));
}

void writePosition(Core &core, std::uint32_t lba, const std::array<std::uint8_t, 8> &position) {
  for (std::uint32_t byte = 0; byte < position.size(); ++byte) {
    core.mem_w8(kStreamPosition + byte, position[byte]);
  }

  // CdControlB(CdlSeekL) receives the location generated by CdIntToPos. Keep the native controller's
  // data-position owner in agreement with that guest-visible value.
  const std::uint32_t absoluteFrame = lba + 150u;
  core.mem_w8(kStreamLocation + 0u, bcd(absoluteFrame / (60u * 75u)));
  core.mem_w8(kStreamLocation + 1u, bcd((absoluteFrame / 75u) % 60u));
  core.mem_w8(kStreamLocation + 2u, bcd(absoluteFrame % 75u));
}

bool startNativeCdStream(
    Core &core, std::uint32_t lba, std::uint32_t readMode, std::uint32_t filter, FieldService serviceField) {
  if (!core.game) {
    cfg_loge("x4-stream-startup", "STR startup requires a bound Game");
    return false;
  }

  // This is CdReset(0)'s completed controller state, without its libcd polling/VSync chain. Preserve
  // the Game wiring and the title's deterministic controller clock across the reset.
  cd_controller::reset(core);
  core.r[4] = 3u;
  serviceFields(core, serviceField, 3u);

  Game &game = *core.game;
  CdcState &controller = game.cdc;
  const std::uint8_t file = static_cast<std::uint8_t>(core.mem_r8(filter));
  const std::uint8_t channel = static_cast<std::uint8_t>(core.mem_r8(filter + 1u));
  xa_stream_stop(&game.xa);
  xa_stream_setfilter(&game.xa, file, channel);
  core.r[4] = 3u;
  serviceFields(core, serviceField, 3u);

  const std::uint8_t mode = static_cast<std::uint8_t>(readMode);
  cd_controller::setMode(core, mode);

  std::array<std::uint8_t, 8> position{};
  if (!disc_get_subq_position(&game.disc, lba, position.data())) {
    cfg_loge("x4-stream-startup", "cannot resolve STR start LBA %u to a disc position", lba);
    return false;
  }
  writePosition(core, lba, position);

  // CdRead2(mode) installs libstr's DMA/ready callbacks when bit 8 is set, publishes the sector
  // framing flag, applies Setmode, then issues ReadS. Preserve those non-wait side effects directly.
  installReadCallbacks(core, readMode);
  game.cd.setloc_lba = static_cast<std::int32_t>(lba);
  game.cd.sec_pos = 0;
  game.cd.sec_len = 0;
  game.cd.sec_lba = -1;
  game.cd.stream_active = 1;
  game.cd.stream_t0_ns = 0;
  game.cd.stream_delivered = 0;
  xa_stream_setloc(&game.xa,
                   static_cast<std::uint8_t>(core.mem_r8(kStreamLocation + 0u)),
                   static_cast<std::uint8_t>(core.mem_r8(kStreamLocation + 1u)),
                   static_cast<std::uint8_t>(core.mem_r8(kStreamLocation + 2u)));
  xa_stream_start(&game.xa);
  cdc_begin_read(&controller, lba);
  core.r[4] = 3u;
  serviceFields(core, serviceField, 3u);
  return true;
}

void finish(Core &core, std::uint32_t result) {
  core.r[2] = result;
  core.r[31] = core.mem_r32(core.r[29] + 48u);
  core.r[19] = core.mem_r32(core.r[29] + 44u);
  core.r[18] = core.mem_r32(core.r[29] + 40u);
  core.r[17] = core.mem_r32(core.r[29] + 36u);
  core.r[16] = core.mem_r32(core.r[29] + 32u);
  core.r[29] += 56u;
  tick(core, 8u);
}

} // namespace

void installReadCallbacks(Core &core, std::uint32_t readMode) {
  if ((readMode & 0x100u) == 0u) {
    return;
  }
  core.mem_w32(kStSectorMode, (readMode & 0x20u) != 0u ? 0u : 1u);
  core.mem_w32(kDmaChannel3CallbackSlot, kStDataReadyCallback);
  core.mem_w32(kReadyCallbackSlot, kStCdInterrupt);
}

void run(Core &core, GuestDispatch dispatch, FieldService serviceField, CdTransaction startCdStream) {
  if (!dispatch || !serviceField || !startCdStream) {
    cfg_loge("x4-stream-startup", "STR startup requires dispatch, field, and CD services");
    std::abort();
  }

  const std::uint32_t streamLba = core.r[4];
  const std::uint32_t streamArg1 = core.r[5];
  const std::uint32_t streamArg2 = core.r[6];
  const std::uint32_t ring = core.r[7];

  core.r[29] -= 56u;
  core.mem_w32(core.r[29] + 44u, core.r[19]);
  core.mem_w32(core.r[29] + 40u, core.r[18]);
  core.mem_w32(core.r[29] + 36u, core.r[17]);
  core.mem_w32(core.r[29] + 32u, core.r[16]);
  core.mem_w32(core.r[29] + 48u, core.r[31]);

  const std::uint32_t ringSize = core.mem_r32(core.r[29] + 72u);
  const std::uint32_t table0 = core.mem_r32(core.r[29] + 76u);
  const std::uint32_t table1 = core.mem_r32(core.r[29] + 80u);
  const std::uint32_t table2 = core.mem_r32(core.r[29] + 84u);
  const std::uint32_t streamFlavor = core.mem_r32(core.r[29] + 88u);
  const std::uint32_t table3 = core.mem_r32(core.r[29] + 92u);

  core.r[19] = streamLba;
  core.r[18] = streamArg1;
  core.r[17] = ringSize;
  core.r[16] = ring;

  core.mem_w32(kStreamArg2, streamArg2);
  core.mem_w32(kVlcTableIndex, 0u);
  core.mem_w32(0x80139634u, 0u);
  core.mem_w32(0x801441C0u, 0u);
  core.mem_w32(kFrameHeaderRemaining, 0u);
  core.mem_w32(kVlcTables + 0u, table0);
  core.mem_w32(kVlcTables + 4u, table1);
  core.mem_w32(kVlcTables + 8u, table2);
  core.mem_w32(kVlcTables + 16u, table3);
  core.mem_w32(kVlcTables + 20u, table3);
  core.mem_w32(kStreamFlavor, streamFlavor);
  tick(core, 39u);

  core.r[4] = 0u;
  call(core, dispatch, kSetStreamMode, 0x80018824u, 0u);
  core.r[4] = 0u;
  call(core, dispatch, kDecDctReset, 0x8001882Cu, 2u);
  core.r[4] = kDecDctOutput;
  call(core, dispatch, kDecDctOutCallback, 0x8001883Cu, 4u);
  core.r[4] = ring;
  core.r[5] = ringSize;
  call(core, dispatch, kStSetRing, 0x80018848u, 3u);
  core.r[4] = core.mem_r32(kVlcTables + 16u);
  core.r[5] = streamArg1;
  core.r[6] = 0x0FFFFFFFu;
  core.r[7] = kStVblankCallback;
  core.mem_w32(core.r[29] + 16u, 0u);
  call(core, dispatch, kStSetStream, 0x8001886Cu, 9u);
  call(core, dispatch, kResetMovieState, 0x80018874u, 2u);
  core.mem_w8(kStreamFilter, 1u);
  core.r[4] = 127u;
  call(core, dispatch, kSetCdVolume, 0x80018888u, 5u);
  core.r[4] = streamLba;
  core.r[5] = kStreamLocation;
  call(core, dispatch, kCdIntToPos, 0x80018898u, 4u);
  core.mem_w32(kStreamStartLba, streamLba);

  const std::uint32_t readMode = core.mem_r32(kStreamFlavor) == 0u ? kDefaultReadMode : kAlternateReadMode;
  if (!startCdStream(core, streamLba, readMode, kStreamFilter, serviceField)) {
    finish(core, 1u);
    return;
  }

  core.r[4] = kStreamPosition + 5u;
  call(core, dispatch, kCdPosToInt, 0x80018968u, 4u);
  const std::uint32_t headLba = core.r[2];
  if (headLba < streamLba - 20u || headLba > streamLba + 5u) {
    finish(core, 1u);
    return;
  }

  call(core, dispatch, kPrepareFirstFrame, 0x8001899Cu, 2u);
  std::uint32_t waits = 0u;
  for (;;) {
    core.r[4] = core.r[29] + 24u;
    core.r[5] = core.r[29] + 28u;
    call(core, dispatch, kStGetNext, 0x800189A8u, 2u);
    if (core.r[2] == 0u) {
      break;
    }
    core.r[4] = 0u;
    serviceFields(core, serviceField, 1u);
    if (++waits >= kFirstFrameWaitLimit) {
      finish(core, 1u);
      return;
    }
  }

  core.mem_w32(kFrameHeaderRemaining, core.mem_r32(kFrameHeaderRemaining) - 1u);
  const std::uint32_t frameHeader = core.mem_r32(core.r[29] + 28u);
  for (std::uint32_t byte = 0u; byte < 32u; ++byte) {
    core.mem_w8(kFrameHeaderCopy + byte, core.mem_r8(frameHeader + byte));
  }

  const auto align16 = [](std::int16_t value) {
    const std::int32_t biased = static_cast<std::int32_t>(value) + (value < -8 ? 23 : 8);
    return static_cast<std::uint16_t>(biased & ~15);
  };
  core.mem_w16(kFrameWidth, align16(static_cast<std::int16_t>(core.mem_r16(kFrameWidth))));
  core.mem_w16(kFrameHeight, align16(static_cast<std::int16_t>(core.mem_r16(kFrameHeight))));

  const std::uint32_t frameData = core.mem_r32(core.r[29] + 24u);
  const std::uint32_t tableIndex = core.mem_r32(kVlcTableIndex);
  core.r[4] = frameData;
  core.r[5] = core.mem_r32(kVlcTables + tableIndex * 4u);
  call(core, dispatch, kDecDctVlc, 0x80018AA0u, 12u);
  core.r[4] = frameData;
  call(core, dispatch, kStFreeRing, 0x80018AACu, 3u);
  finish(core, 0u);
}

void run(Core *core) {
  if (!core) {
    cfg_loge("x4-stream-startup", "STR startup received a null Core");
    std::abort();
  }
  run(*core, guest::call, awaitField, startNativeCdStream);
}

void registerOverride(Core &core) {
  guest::install(core, kEntry, "stream_startup::startStr", static_cast<void (*)(Core *)>(run));
}

} // namespace x4::stream_startup
